### ISSUE TITLE
Missing image file is included as img tag without the src attribute

### ISSUE THREAD

**Issue by realcharmer** [filiprojek/walauncher#3]
When an image file is defined in the `config.json` and the file is not found, the generated HTML contains an image tag without the `src` attribute. This results in a non-centered text in the navigation button as well as invalid HTML, since the `src` attribute is required.

![image](https://github.com/user-attachments/assets/50b3e6d3-5aea-4042-ae28-71bdcc8a534a)

Generated code:

```
<span><img alt=""><p>Prowlarr</p></span>
```

Expected behavior is to not generate the `img` tag at all, when the source file is not found:

```
<span><p>Prowlarr</p></span>
```

Also the paragraph makes no sense here, but that is out of scope here.

**Comment by filiprojek** [comment]
@realcharmer  Thanks!
